### ISSUE TITLE
Introduction at the website is different then on pub

### ISSUE THREAD

**Issue by kasperpeulen** [MikeMitterer/dart-material-design-lite#11]
see: http://www.material-design-lite.pub/#/gettingstarted

it says that I need those dependencies:

```
dependencies:
  browser: any
  logging: any
  logging_handlers: any
  console_log_handler: any
  mdl: any
```

but I don't think I need all of those.

And here it says something different:
https://pub.dartlang.org/packages/mdl
