### ISSUE TITLE
dialogs seem to only work correctly in fulbleed application

### ISSUE THREAD

**Issue by kasperpeulen** [MikeMitterer/dart-material-design-lite#15]
see this source code to reproduce, there is an button at the end of the file, if you click it, you will see the dialog at the beginning of the file
https://gist.github.com/kasperpeulen/5b5ef42af195a4216971

**Comment by kasperpeulen** [comment]
![](http://i.imgur.com/1xlLs5l.gif)

**Comment by kasperpeulen** [comment]
doesn't seem to happen with paper dialogs from polymer 1:
https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html&active=paper-dialog

**Comment by MikeMitterer** [comment]
Hm I don't get it??

> you will see the dialog at the beginning of the file
> Which file - your html?

**Comment by kasperpeulen** [comment]
Oh I mean, you see the dialog at the beginning of the screen.
Just run the gist and you will see it yourself.
I think this could be fixed by changing position absolute, to position fixed.

**Comment by MikeMitterer** [comment]
It works if you add

``` css
        .mdl-dialog-container {
            position: absolute;
            width: 100%;
            height: 2050px;
        }

        .mdl-dialog-container .mdl-dialog {
            position: fixed;
            margin-left: -144px;
            margin-right: auto;
            margin-top: calc(50vh - 174px / 2);
        }
```

quite "hacky", I know - but at least it's a solution. 

Sorry - I don't add an option for this to the framework. (At least not at the moment - maybe in the future if there are more requests in that direction).

![screenshot-1835](https://cloud.githubusercontent.com/assets/116654/9352369/1631642a-4661-11e5-8274-4fe59fec3357.png)
