### ISSUE TITLE
Is it incompatible with latest Angular2-dart beta?

### ISSUE THREAD

**Issue by aleksfes** [MikeMitterer/dart-material-design-lite#35]
Hi, guys!

I faced with problem while trying to install both Angular 2 beta and dart-material-design-lite.

By default I have no problem:

``` yaml
name: dartNg2MdlTest
version: 0.0.1
description: Angular 2 and Material Design Lite are not compatible?
dependencies:
  angular2:
  mdl:
```

By default angular2 version is pretty old:

``` text
0  ~/dev/dart-ng2-mdl ...feoktistov $ pub get | grep -e "angular" -e "mdl"
+ angular2 2.0.0-alpha.30 (2.0.0-beta.18 available)
+ mdl 1.17.4
Loading angular2 and di/module_transformer transformers...
Loading mdl transformers...
Precompiled angular2, dart_style, di, intl and mdl.
```

If I will fix latest angular2 beta,

``` yaml
dependencies:
  angular2: 2.0.0-beta.18
  mdl:
```

the error will appear:

``` text
0  ~/dev/dart-ng2-mdl ...feoktistov $ pub get
Resolving dependencies... (10.2s)
Package di has no versions that match >=3.3.0 <4.0.0 derived from:
- mdl 1.17.4 depends on version ^3.3.0
```

Should I report this bug to the Angular2-dart project too?
What should I do to fix this issue?
